CREATE DATABASE `cricketclub`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAIL_ID` VARCHAR(50) NOT NULL DEFAULT '',
  `CONTACT_NO` VARCHAR(45) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(200) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `EMPLOYEE_ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `DESIGNATION` VARCHAR(45) NOT NULL DEFAULT '',
  `LEVEL` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `ACTIVE` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(USERNAME,EMAIL_ID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

INSERT INTO registration( NAME, ADDRESS, CONTACT_NO, EMAIL_ID, USERNAME, PASSWORD, EMPLOYEE_ID, LEVEL, ACTIVE, DESIGNATION)
VALUES ('admin', '', '','admin@admin.com', 'admin', 'admin', 0, 1, 'YES', '');

DROP TABLE IF EXISTS `ticket`;
CREATE TABLE `ticket` (
  `TICKETID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EVENTNAME` VARCHAR(45) NOT NULL,
  `EVENTTYPE` VARCHAR(45) NOT NULL DEFAULT '',
  `EVENTDATE` VARCHAR(45) NOT NULL DEFAULT '',
  `EVENTTIME` VARCHAR(45) NOT NULL,
  `EVENTPLACE` VARCHAR(200) NOT NULL DEFAULT '',
  `PRICE` DOUBLE NOT NULL DEFAULT 0,
  `AVAILABLE` INT(10) NOT NULL DEFAULT 0,
  `BOOKED` INT(10) NOT NULL DEFAULT 0,
  `STATUS` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(EVENTNAME),
  PRIMARY KEY (`TICKETID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
  `BOOKID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EVENTNAME` VARCHAR(45) NOT NULL,
  `EVENTTYPE` VARCHAR(45) NOT NULL DEFAULT '',
  `EVENTDATE` VARCHAR(45) NOT NULL DEFAULT '',
  `EVENTTIME` VARCHAR(45) NOT NULL,
  `EVENTPLACE` VARCHAR(200) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(45) NOT NULL,
  `BOOKING` INT(10) NOT NULL DEFAULT 0,
  `PRICE` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`BOOKID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `feedback`;
CREATE TABLE `feedback` (
  `FEEDBACKID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EVENTNAME` VARCHAR(45) NOT NULL,
  `EMAILID` VARCHAR(50) NOT NULL DEFAULT '',
  `FEEDBACKBY` VARCHAR(45) NOT NULL DEFAULT '',
  `COMMENTS` VARCHAR(500) NOT NULL DEFAULT '',
  `RATING` INT(2) NOT NULL DEFAULT 0,
  UNIQUE(EVENTNAME, FEEDBACKBY, EMAILID),
  PRIMARY KEY (`FEEDBACKID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;
