CREATE DATABASE `trafficviolation`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAIL_ID` VARCHAR(50) NOT NULL DEFAULT '',
  `CONTACT_NO` VARCHAR(45) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(200) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `EMPLOYEE_ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `DESIGNATION` VARCHAR(45) NOT NULL DEFAULT '',
  `LEVEL` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `ACTIVE` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(USERNAME,EMAIL_ID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

INSERT INTO registration( NAME, ADDRESS, CONTACT_NO, EMAIL_ID, USERNAME, PASSWORD, EMPLOYEE_ID, LEVEL, ACTIVE, DESIGNATION)
VALUES ('admin', '', '','admin@admin.com', 'admin', 'admin', 0, 1, 'YES', '');

DROP TABLE IF EXISTS `vehicle`;
CREATE TABLE `vehicle` (
  `VEHICLEID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `OWNERNAME` VARCHAR(45) NOT NULL,
  `REGNO` VARCHAR(45) NOT NULL DEFAULT '',
  `REGDATE` VARCHAR(45) NOT NULL DEFAULT '',
  `DLNO` VARCHAR(45) NOT NULL,
  `ADDRESS` VARCHAR(200) NOT NULL DEFAULT '',
  `CHARSSISNO` VARCHAR(45) NOT NULL,
  `ENGINENO` VARCHAR(45) NOT NULL,
  `MODEL` VARCHAR(45) NOT NULL,
  `COLOR` VARCHAR(15) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(ENGINENO),
  PRIMARY KEY (`VEHICLEID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `complaint`;
CREATE TABLE `complaint` (
  `COMPLAINTID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `REGNO` VARCHAR(45) NOT NULL DEFAULT '',
  `PAYMENTTYPE` VARCHAR(45) NULL DEFAULT '',
  `PAYMENTDATE` VARCHAR(45) NULL DEFAULT '',
  `FEE` DOUBLE NOT NULL default 0,
  `REASON` VARCHAR(45) NOT NULL DEFAULT '',
  `STATUS` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`COMPLAINTID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;
