CREATE DATABASE `facebookapp`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(250) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `login`;
CREATE TABLE `login` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ONLINE` BOOLEAN NOT NULL DEFAULT FALSE,
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `friendrequests`;
CREATE TABLE `friendrequests` (
  `USERID` BINARY(36) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL,
  `FRIENDID` BINARY(36) NOT NULL,
  `REQUESTEDDATE` DATE NOT NULL,
  UNIQUE (`USERID`,`FRIENDID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `linkedfriends`;
CREATE TABLE `linkedfriends` (
  `USERID` BINARY(36) NOT NULL,
  `REQUESTORID` BINARY(36) NOT NULL,
  `ACCEPTEDDATE` DATE NOT NULL,
  UNIQUE (`USERID`,`REQUESTORID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `postdetails`;
CREATE TABLE `postdetails` (
  `POSTID` BINARY(36) NOT NULL,
  `USERID` BINARY(36) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `TITLE` VARCHAR(100) NOT NULL DEFAULT '',
  `CREATEDDATE` DATETIME NOT NULL,
  `PATH` VARCHAR(250) NOT NULL DEFAULT '',
  `MESSAGE` VARCHAR(500) NOT NULL DEFAULT '',
  `VISIBILITYLEVEL` INT NOT NULL DEFAULT 0,
  `LIKECOUNT` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (POSTID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `likehistory`;
CREATE TABLE `likehistory` (
  `POSTID` BINARY(36) NOT NULL,
  `USERID` BINARY(36) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  UNIQUE (POSTID, USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;