CREATE DATABASE `bugtracksystem`;

DROP TABLE IF EXISTS `employee`;
CREATE TABLE `employee` (
  `EMPLOYEEID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(50) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(45) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(200) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `DESIGNATION` VARCHAR(45) NOT NULL DEFAULT '',
  `LEVEL` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `ACTIVE` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (`EMPLOYEEID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

INSERT INTO employee( NAME, ADDRESS, CONTACTNO, EMAILID, USERNAME, PASSWORD, LEVEL, ACTIVE)
             VALUES ('admin', '', '','admin@admin.com', 'admin', 'admin', 1, 'YES' );

DROP TABLE IF EXISTS `ticket`;
CREATE TABLE `ticket` (
  `TICKETID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `ASSIGNTO` VARCHAR(45) NOT NULL DEFAULT '',
  `FILEPATH` VARCHAR(100) NOT NULL DEFAULT '',
  `FILENAME` VARCHAR(45) NOT NULL,
  `ASSIGNFROM` VARCHAR(45) NOT NULL DEFAULT '',
  `LASTDATE` VARCHAR(45) NOT NULL,
  `ROOTCAUSE` VARCHAR(500) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(500) NOT NULL DEFAULT '',
  UNIQUE(FILENAME),
  PRIMARY KEY (`TICKETID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;



