DROP TABLE IF EXISTS `employeedetails`;
CREATE TABLE `employeedetails` (
  `PKEMPLOYEE_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `EMPLOYEE_NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMP_JOINDATE` DATE DEFAULT NULL,
  `QUALIFICATION` VARCHAR(45) DEFAULT NULL,
  `EMAILID` VARCHAR(50) DEFAULT NULL,
  `CONTACTNO` VARCHAR(45) DEFAULT NULL,
  `FATHERNAME` VARCHAR(100) DEFAULT NULL,
  `MOTHERNAME` VARCHAR(100) DEFAULT NULL,
  `ADDRESS` VARCHAR(200) DEFAULT NULL,
  `DOB` VARCHAR(45) DEFAULT NULL,
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `DESIGNATION` VARCHAR(45) DEFAULT NULL,
  `RELIVINGDATE` DATE DEFAULT NULL,
  `LEVEL` INT(10) UNSIGNED DEFAULT NULL,
  `ACTIVE` VARCHAR(45) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAIL_ID` VARCHAR(50) DEFAULT NULL,
  `CONTACT_NO` VARCHAR(45) DEFAULT NULL,
  `ADDRESS` VARCHAR(200) DEFAULT NULL,
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `DESCRIPTION` VARCHAR(45) DEFAULT NULL,
  `LEVEL` INT(10) UNSIGNED DEFAULT NULL,
  `STATUS` VARCHAR(45) DEFAULT NULL,
  UNIQUE(USERNAME,EMAIL_ID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;
