DROP TABLE IF EXISTS `employeedetails`;
CREATE TABLE `employeedetails` (
  `PKEMPLOYEE_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `EMPLOYEE_NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMP_JOINDATE` DATE DEFAULT NULL,
  `QUALIFICATION` VARCHAR(45) DEFAULT NULL,
  `EMAILID` VARCHAR(50) DEFAULT NULL,
  `CONTACTNO` VARCHAR(45) DEFAULT NULL,
  `FATHERNAME` VARCHAR(100) DEFAULT NULL,
  `MOTHERNAME` VARCHAR(100) DEFAULT NULL,
  `ADDRESS` VARCHAR(200) DEFAULT NULL,
  `DOB` VARCHAR(45) DEFAULT NULL,
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `DESIGNATION` VARCHAR(45) DEFAULT NULL,
  `RELIVINGDATE` DATE DEFAULT NULL,
  `LEVEL` INT(10) UNSIGNED DEFAULT NULL,
  `ACTIVE` VARCHAR(45) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAIL_ID` VARCHAR(50) DEFAULT NULL,
  `CONTACT_NO` VARCHAR(45) DEFAULT NULL,
  `ADDRESS` VARCHAR(200) DEFAULT NULL,
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(45) NOT NULL DEFAULT '',
  `DESCRIPTION` VARCHAR(45) DEFAULT NULL,
  `LEVEL` INT(10) UNSIGNED DEFAULT NULL,
  `ACTIVE` VARCHAR(45) DEFAULT NULL,
  UNIQUE(USERNAME,EMAIL_ID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

INSERT INTO registration( NAME, ADDRESS, CONTACT_NO, EMAIL_ID, USERNAME, PASSWORD, LEVEL, ACTIVE, DESCRIPTION)
VALUES ('admin', '', '','admin@admin.com', 'admin', 'admin', 1, 'YES', '');

INSERT INTO registration( NAME, ADDRESS, CONTACT_NO, EMAIL_ID, USERNAME, PASSWORD, LEVEL, ACTIVE, DESCRIPTION)
VALUES ('abc', '', '','abc@abc.com', 'abc', 'abc', 3, 'YES', '');

INSERT INTO registration( NAME, ADDRESS, CONTACT_NO, EMAIL_ID, USERNAME, PASSWORD, LEVEL, ACTIVE, DESCRIPTION)
VALUES ('xyz', '', '','xyz@xyz.com', 'xyz', 'xyz', 2, 'YES', '');


DROP TABLE IF EXISTS `shopdetails`;
CREATE TABLE `shopdetails` (
  `PKORGANISATION_ID` int(10) NOT NULL AUTO_INCREMENT,
  `SHOP_NAME` varchar(100) NOT NULL default '',
  `ADDRESS` varchar(80) default NULL,
  `CITY` varchar(45) default NULL,
  `STATE` varchar(45) default NULL,
  `COUNTRY` varchar(45) default NULL,
  `PINCODE` varchar(45) default NULL,
  `STARTDATE` varchar(45) default NULL,
  PRIMARY KEY (PKORGANISATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
