CREATE DATABASE `facebookapp`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(250) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `login`;
CREATE TABLE `login` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ONLINE` BOOLEAN NOT NULL DEFAULT FALSE,
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

INSERT INTO registration (`USERID`,`NAME`,`EMAILID`,`CONTACTNO`,`ADDRESS`,`USERNAME`,`PASSWORD`, `ACTIVE`)
VALUES (UUID(), 'nayan', 'nayan.savi@gmail.com', '7411069748', 'Bangalore', 'nayan', MD5('nayan'), TRUE);

INSERT INTO login (`USERID`,`NAME`,`EMAILID`,`CONTACTNO`,`ONLINE`,`USERNAME`,`PASSWORD`,  `ACTIVE`)
VALUES (UUID(), 'nayan', 'nayan.savi@gmail.com', '7411069748', FALSE, 'nayan', MD5('nayan'), TRUE);

DROP TABLE IF EXISTS `friendrequests`;
CREATE TABLE `friendrequests` (
  `USERID` BINARY(36) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL,
  `FRIENDID` BINARY(36) NOT NULL,
  `REQUESTEDDATE` DATE NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `linkedfriends`;
CREATE TABLE `linkedfriends` (
  `USERID` BINARY(36) NOT NULL,
  `REQUESTORID` BINARY(36) NOT NULL,
  `ACCEPTEDDATE` DATE NOT NULL DEFAULT ''
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `postdetails`;
CREATE TABLE `postdetails` (
  `USERID` BINARY(36) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `TITLE` VARCHAR(100) NOT NULL DEFAULT '',
  `CREATEDDATE` DATE NOT NULL DEFAULT '',
  `PATH` VARCHAR(250) NOT NULL DEFAULT '',
  `MESSAGE` VARCHAR(500) NOT NULL DEFAULT '',
  `VISIBILITYLEVEL` INT NOT NULL DEFAULT '',
  `LIKE` INT NOT NULL DEFAULT 0
) ENGINE=INNODB DEFAULT CHARSET=latin1;