CREATE DATABASE `facebookapp`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `USERID` BINARY(16) NOT NULL,
  `NAME` VARCHAR(90) NOT NULL DEFAULT '',
  `EMAIL_ID` VARCHAR(50) NOT NULL DEFAULT '',
  `CONTACT_NO` VARCHAR(45) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(200) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(45) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(32) NOT NULL DEFAULT '',
  `ONLINE` BOOLEAN NOT NULL DEFAULT FALSE,
  `ACTIVE` VARCHAR(45) NOT NULL DEFAULT '',
  UNIQUE(USERNAME,EMAIL_ID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

