CREATE DATABASE `pizzaapp`;

DROP TABLE IF EXISTS `registration`;
CREATE TABLE `registration` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `ADDRESS` VARCHAR(250) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `login`;
CREATE TABLE `login` (
  `USERID` BINARY(36) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL DEFAULT '',
  `EMAILID` VARCHAR(30) NOT NULL DEFAULT '',
  `CONTACTNO` VARCHAR(10) NOT NULL DEFAULT '',
  `USERNAME` VARCHAR(30) NOT NULL DEFAULT '',
  `PASSWORD` VARCHAR(35) NOT NULL DEFAULT '',
  `ONLINE` BOOLEAN NOT NULL DEFAULT FALSE,
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE ,
  UNIQUE(USERNAME,EMAILID),
  PRIMARY KEY (USERID)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

